[package]
name = "orbit-tui"
version = "0.0.1"
edition = "2021"

[dependencies]
orbit-core = { git = "https://github.com/juiceppe/orbit-core"}
tokio = { version = "1.49", features = ["full"] }
ratatui = "0.30.0"
crossterm = "0.29.0"